### ISSUE TITLE
Some settings enquiry

### ISSUE THREAD

**Issue by joeyoon80** [cryptocoyns/daytradingmethod#1]
Hi, just wanted enquire on the settings in your latest version.

Example, in DCA file, enabled = true/false no longer is applicable, isnt it?

Also, in DCA file, min_buy_balance = 0 is repeated.

I noticed in your DCA, there is no trailing_buy = x, is this intentional?

Also, ALL_sell_only_mode_override = true dont seem to exist in the wiki. Can u confirm such a setting exist? If it does then probably wiki needs to be updated.

**Comment by cryptocoyns** [comment]
Joey, thank you for pointing those out. I will correct in the new v1.0.5 settings.
DCA enabled is a hangover I will fix it.
ALL_sell_only_mode_override = true doesn't exist it was a feature request I was asking for, I just forgot to remove it. Using the URL override for now. I want the bot to trade all the time regardless of market conditions.
Trailing was something I was experimenting with to see what the defaults would do.
