### ISSUE TITLE
Typo in trailing_profit

### ISSUE THREAD

**Issue by bensinther** [cryptocoyns/daytradingmethod#2]
Just saw that the "ALL_trailing_profit" is written like this "ALL_trai**n**ing_profit"

It's inside the HIGHBB Buy settings in PAIRS

````
ALL_sell_strategy =  HIGHBB
ALL_sell_value = 30
ALL_min_profit = 0.75
ALL_training_profit = 0.25
````

**Comment by cryptocoyns** [comment]
Thanks for that it has been fixed in new version coming out shortly v1.0.6
