### ISSUE TITLE
"illegally forking"

### ISSUE THREAD

**Issue by edgarsala** [cryptocoyns/daytradingmethod#3]
There is no such thing like illegally forking, you also can make it private and restrict access. If its public, users can fork whatever they want.

**Comment by cryptocoyns** [comment]
Actually there is. You may wish to discuss that with GitHub who have a policy around that, they will remove forks if requested by the Copyright holder as they can be exposed to fines for it if they dont. Copyright law is very specific about people taking complete copies it carries with it a USD$150,000 fine. As a commercial entity we do enforce our copyright. https://help.github.com/articles/dmca-takedown-policy/
